export const environment = {
  production: true,
  baseUrl: '/user-api/api',
  baseUrlAppointment: '/qms-api/api',
  dashboardBaseURL: '/emr-api/api',
  jsonPath: '/assets/JSON/',
  userNotificationUrl: '/hosted-service/userNotificationHub',
  limitDataToGetFromServer: 100,
  REPORT_API: '/qms-report',
  LoginLogoUrl: '/file-server/HospitalImage/',
  EMR_BaseURL: 'http://drrescribe.com/medsonit-be',
  STATIC_JSON_URL: './assets/JSON/',
  IMG_PATH: './assets/images',
  FILE_SERVER_IMAGE_URL: '/file-server',
  SNOWMED_URL: 'http://172.16.100.71:8181/browser/MAIN',
  SNOWMED_SEMANTIC_TAG_URL: 'http://172.16.100.71:8181/MAIN',
  SSO_LOGIN_URL: '/user-web',
  HIS_Add_PatientCommon_API:'/hmis-web',
  notificationPartialUrl: '/user-web/#/partial-notification-list/#token#/#source#',
  HIS_WEB_APP_URL: '/hmis-web',
  HIS_FE_APP_URL: '/hmis-fe',
};
