export const environment = {
  production: true,
  baseUrl: '/user-api/api',
  baseUrlAppointment: '/qms-api/api',
  dashboardBaseURL: '/emr-api/api',
  jsonPath: './assets/JSON/',
  appointmentsUrl: '/qms-api/appointments/#/entitySchedule/',
  baseUrlAppointmentForDisplayTemplate9: '/hosted-service/api',
  tvDisplayUrl: '/hosted-service/notificationHub',
  appointmentHubUrl: '/hosted-service/appointmentHub',
  charServerUrl: '/hosted-service/ChatHub',
  notificationUrl: '/hosted-service/userNotificationHub',
  limitDataToGetFromServer: 100,
  REPORT_API: '/qms-report',
  LoginLogoUrl: '/file-server/HospitalImage/',
  EMR_BaseURL: 'http://drrescribe.com/medsonit-be',
  IMG_PATH: './assets/images',
  FILE_SERVER_IMAGE_URL: '/file-server',
  SNOWMED_URL: 'http://172.16.100.71:8181/browser/MAIN',
  SNOWMED_SEMANTIC_TAG_URL: 'http://172.16.100.71:8181/MAIN',
  HIS_Add_PatientCommon_API:'/hmis-web',
  HIS_FE_APP_URL: '/hmis-fe/#/',
  SSO_LOGIN_URL: '/user-web',
  notificationPartialUrl: '/user-web/#/partial-notification-list/#token#'
};
